### ISSUE TITLE
How to use it without the ">>>" prompt?

### ISSUE THREAD

**Issue by danimesq** [octacian/timecalc#1]
The ">>>" prompt that appear when using a command like "./timecalc 14:50:40.00 - 00:15:11.70" instead of the results, affects the programmatic use of timecalc.
@octacian

**Comment by danimesq** [comment]
Solution by [Arkadiusz](https://askubuntu.com/a/1447366/1255788): `echo 14:50:40.00 - 00:15:11.70 | ./timecalc | head -n1 | sed 's,^>>> ,,'`

**Comment by octacian** [comment]
Hey @danimesq! Oh man, I'm really sorry this issue got completely ignored. I've not really been present on GitHub these days 😅 

I see you've got a solution, but I've implemented what I hope is a better one in commit 67b9ce77818276bcfbe8ad6fe39139bc468cc068.

You can now use TimeCalc in eval mode for programmatic scenarios, for example:
```bash
$ timecalc -e 10:22 - 5:28
04:54
```

I do want to give some fair warning: the core of timecalc *really* needs to be reimplemented. It has some weird glitches with multiplication (I think) and doesn't support proper order of operations. I'd love to tackle this at some point soon, but I don't know if that's realistic. So I'll just say that I'd like to fix this sometime this year.

In the meantime, I'm happy it's been useful to you and I hope this helps!
